name: pulumi-ci

on:
  push:
    branches:
      - main

jobs:
  update:
    name: update pulumi infra
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        id: checkout
        uses: actions/checkout@v4

      - name: setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: install dependencies
        id: install-dependencies
        run: npm install

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: run pulumi up
        id: pulumi-up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: stg
          cloud-url: s3://pulumi-state-guigo-ftr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PULUMI_CONFIG_PASSPHRASE: ""
