name: pulumi-ci

on:
  push:
    branches:
      - main

jobs:
  update:
    name: update pulumi infra
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        id: checkout
        uses: actions/checkout@v4

      - name: setup node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: install dependencies
        id: install-dependencies
        run: npm install

      - name: configure aws credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
